Improve state management
PrestaShop/autoupgrade pull request #1046
Opened 2024-11-27 17:11 UTC by M0rgan01

| Questions         | Answers
| ------------------| -------------------------------------------------------
| Description?      | Improve state management
| Type?             | improvement
| BC breaks?        | no
| Deprecations?     | no
| Fixed ticket?     | -
| Sponsor company   | -
| How to test?      | Previous configuration are no longer taken into account, gog files are no longer cut during an update

2024-11-27 17:13 UTC, ga-devfront requested changes

2024-11-27 17:13 UTC, ga-devfront commented on classes/State.php
>      }
you can change this methods to private method and only save on `setBackupName`

2024-11-27 17:33 UTC, Quetzacoalt91 approved these changes, later dismissed

2024-11-28 07:49 UTC, ga-devfront approved these changes, later dismissed

2024-11-28 08:00 UTC, M0rgan01 commented on classes/Commands/UpdateCommand.php
> +        if (strpos($lastInfo, self::$defaultName) !== false) {
this posed a problem if options were placed before the command (ex: `bin/console -v update:start`)

2024-11-28 08:01 UTC, M0rgan01 commented on classes/Commands/UpdateCommand.php
> +                $this->upgradeContainer->getFileConfigurationStorage()->clean(UpgradeFileNames::CONFIG_FILENAME);
We could end up with the config of an old update

2024-12-03 14:58 UTC, ga-devfront approved these changes

2024-12-03 15:43 UTC, Quetzacoalt91 commented
Result of the logs folder after an update:

```
root@b653c57bea07:/var/www/html/admin-dev/autoupgrade/logs# ls -lh
total 3.3M
-rw-r--r-- 1 www-data www-data 3.3M Dec  3 15:35 2024-12-03-163132-update.txt
```

And the log file has the whole process. We're ready to merge!

2024-12-03 15:48 UTC, merged