Add logs email receivers in configuration table
PrestaShop/autoupgrade pull request #436
Opened 2021-11-24 09:33 UTC by rsoulard-prolaser

| Questions         | Answers
| ------------------| -------------------------------------------------------
| Description?      | "Error: invalid e-mail address" when opening modules page in debug mode after upgrade to 1.7.8
| Type?             | bug fix
| BC breaks?        | no
| Deprecations?     | no
| Fixed ticket?     | Fixe https://github.com/PrestaShop/PrestaShop/issues/26680
| How to test?      | Upgrade PrestaShop to 1.7.8 in debug mode and go to the module page
| Possible impacts? | no

2021-12-03 09:46 UTC, matks commented
We can only validate your PR if we have a clear, reproducible scenario we can follow to observe the bug. In order to be able to explore your PR, to verify any side-effects, to make sure it is correct, we need a complete understanding of it, and so does the QA team. That's why a list of steps "1. do this 2. do then that 3. we should see ... but instead we should see ..." is a must-have needed for us to verify the bug 😉 . So before we review the PR we need the bug report confirmed.

2021-12-03 09:46 UTC, matks requested changes
Need confirmed bug report

2021-12-03 14:31 UTC, matks commented
PHPStan issue not related to change https://github.com/PrestaShop/PrestaShop/issues/26861

2021-12-27 14:42 UTC, MatShir commented
Issue updated

2021-12-27 15:04 UTC, PierreRambaud commented on upgrade/sql/1.7.8.0.sql
> +INSERT IGNORE INTO `PREFIX_configuration` (`name`, `value`, `date_add`, `date_upd`) VALUES ('PS_LOGS_EMAIL_RECEIVERS', (SELECT `value` FROM `PREFIX_configuration` WHERE `name` = 'PS_SHOP_EMAIL'), NOW
It should be in the 1.7.8.3.sql script too
Otherwise, upgrading to 1.7.8.3 from 1.7.8.2 will have no effect

2021-12-27 15:04 UTC, PierreRambaud requested changes
It should be in 1.7.8.3.sql script

2021-12-28 08:28 UTC, rsoulard-prolaser commented
Hello @PierreRambaud, it's done.

2021-12-28 08:49 UTC, PierreRambaud approved these changes

2021-12-29 08:13 UTC, Progi1984 submitted a review, later dismissed

2021-12-29 13:28 UTC, marwachelly commented
Hello,

I tested the PR with upgrade from 1.7.7.3 to 1.7.8.2 but the issue is not fixed 
https://watch.screencastify.com/v/z4Mi8udTXGKT7J3u18t3

Could you please check?

Many thanks,

2021-12-29 13:38 UTC, rsoulard-prolaser commented
Hello @marwachelly,

The fix has been moved in the update script to version 1.7.8.3
Can you test on an update to 1.7.8.3?

Thanks

2022-01-03 08:27 UTC, PierreRambaud approved these changes

2022-01-03 14:58 UTC, marwachelly commented
Hello @rsoulard-prolaser 

I created the version 1.7.8.3 from 1.7.8.x then I tested the PR with autoupgrade from 1.7.7.8 to 1.7.8.3 
While the upgrade I faced the attached error 
![image](https://user-images.githubusercontent.com/89604350/147945492-f5f3b540-fcee-4ac0-a68d-be52e738963c.png)

And the issue is still not resolved as shown bellow

https://watch.screencastify.com/v/8Ele0AX9wzi3xDaixD6p

Could you please check?

2022-01-03 15:27 UTC, rsoulard-prolaser commented
Hello @marwachelly,

I have update the script,

Thanks

2022-01-04 08:57 UTC, PierreRambaud reviewed
Why not doing an insert select instead :thinking:

2022-01-04 09:34 UTC, rsoulard-prolaser commented
The previous error confused me with the "select" in the "insert"...

2022-01-10 15:36 UTC, PierreRambaud approved these changes

2022-01-13 16:53 UTC, atomiix approved these changes

2022-01-20 12:47 UTC, marwachelly commented
Hello,
I tested the PR with upgrade from 1.7.7.8 and 1.7.7.3  following the steps bellow and the issue is resolved
1. Open BO 1.7.7.8 /1.7.7.3
2. Go to Logs page and change the minimum severity level to 2
3. Install this module: logger.zip
4. Complete 1 click upgrade to 1.7.8.3 (created from 1.7.8.x branch)
5. Login
6. Enable debug
7. LOGOUT
8. Login => unable to login
https://watch.screencastify.com/v/bzfZXBIO6Hge35kChtNI
https://watch.screencastify.com/v/7PvMFwPdC8BrB5OEFCKh

Thank you @rsoulard-prolaser

2022-01-20 13:01 UTC, marwachelly approved these changes
Hello,
I tested the PR with upgrade from 1.7.7.8 and 1.7.7.3 following the steps bellow and the issue is resolved

1. Open BO 1.7.7.8 /1.7.7.3
2. Go to Logs page and change the minimum severity level to 2
3. Install this module: logger.zip
4. Complete 1 click upgrade to 1.7.8.3 (created from 1.7.8.x branch)
5. Login
6. Enable debug
7. LOGOUT
8. Login => unable to login

https://watch.screencastify.com/v/bzfZXBIO6Hge35kChtNI
https://watch.screencastify.com/v/7PvMFwPdC8BrB5OEFCKh
Thank you @rsoulard-prolaser

2022-01-20 13:30 UTC, merged

2022-01-20 13:30 UTC, PierreRambaud commented
Thank you @rsoulard-prolaser