Updated PREFIX_state.name field to 80 chars.
PrestaShop/autoupgrade pull request #455
Opened 2022-01-26 06:45 UTC by rickygzz

Fixes https://github.com/PrestaShop/PrestaShop/issues/27156 updating size to 80 chars for PREFIX_state.name field.

| Questions         | Answers
| ------------------| -------------------------------------------------------
| Description?      | Updating PREFIX_State.name field to 80 chars according to PR https://github.com/PrestaShop/PrestaShop/pull/27162
| Type?             | improvement
| BC breaks?        | yes
| Deprecations?     | no
| Fixed ticket?     | Fixes https://github.com/PrestaShop/PrestaShop/issues/27156.
| How to test?      | This PR should be approved at the same time as PR https://github.com/PrestaShop/PrestaShop/pull/27162 which changes the field size to 80 chars.
| Possible impacts? | None that I know of.

2022-02-03 21:01 UTC, eternoendless requested changes

2022-02-03 21:01 UTC, eternoendless commented on upgrade/sql/8.0.0.sql
> +ALTER TABLE `PREFIX_state` MODIFY COLUMN `name` VARCHAR(80) NOT NULL;
This part must be removed

2022-02-08 08:37 UTC, rickygzz commented
@eternoendless  Sorry, I had to force-push the changes.

Now this PR just creates `upgrade/sql/1.7.8.4.sql` file as requested.

2022-02-08 14:40 UTC, eternoendless approved these changes

2022-02-08 14:42 UTC, eternoendless commented
All good! Thank you @rickygzz

2022-02-08 14:42 UTC, merged

2022-04-08 08:16 UTC, khouloudbelguith commented
Hi @PrestaShop/prestashop-maintainers,

The origin [PR](https://github.com/PrestaShop/PrestaShop/pull/27162) core is added to the 1.7.8.6 milestone.
But, the autoupgrade PR is added to 1.7.8.4. sql.
What do you think?

Thanks!

2022-04-08 08:22 UTC, kpodemski commented
We have to move this sql query to 1.7.8.6.sql and next time we probably need to merge `autoupgrade` related PRs **after** the original PR 👍