Add displayCheckoutBeforeConfirmation hook
PrestaShop/autoupgrade pull request #458
Opened 2022-02-03 09:50 UTC by Hlavtox

| Questions         | Answers
| ------------------| -------------------------------------------------------
| Description?      | Add new https://github.com/PrestaShop/PrestaShop/pull/27437 hook during upgrade
| Type?             | new feature
| BC breaks?        | no
| Deprecations?     | no
| Fixed ticket?     | -
| How to test?      | Install a new shop, make an upgrade to 8.0.0, check the hook is in DB
| Possible impacts? | No

2022-02-03 09:56 UTC, kpodemski submitted a review, later dismissed

2022-02-03 09:58 UTC, saulaski submitted a review, later dismissed

2022-02-08 13:49 UTC, PululuK approved these changes

2022-02-08 13:50 UTC, PululuK commented
The main PR as been merger : https://github.com/PrestaShop/PrestaShop/pull/27437

2022-02-21 15:52 UTC, okom3pom approved these changes

2022-02-21 19:58 UTC, hibatallahAouadni commented
Hello @Hlavtox 

Could you please provide steps to test the PR :pray: 
And please rebase your PR.

Thanks!

2022-03-24 13:12 UTC, Hlavtox commented
Rebased

2022-04-04 14:01 UTC, matks submitted a review, later dismissed

2022-04-05 12:31 UTC, hibatallahAouadni reviewed
Hello @Hlavtox 

I encountred an issue with your PR while upgrading my shop from 1.7.8.3 to 8.0.0:

`SQL 8.0.0 1064 in INSERT IGNORE INTO `ps_hook` (`id_hook`, `name`, `title`, `description`, `position`) VALUES (NULL, 'actionValidateOrderAfter', 'New Order', 'This hook is called after validating an order by core', '1'), (NULL, 'actionAdminOrdersTrackingNumberUpdate', 'After setting the tracking number for the order', 'This hook allows you to execute code after the unique tracking number for the order was added', '1'), (NULL, 'actionAdminSecurityControllerPostProcessBefore', 'On post-process in Admin Security Controller', 'This hook is called on Admin Security Controller post-process before processing any form', '1'), (NULL, 'actionAdminSecurityControllerPostProcessGeneralBefore', 'On post-process in Admin Security Controller', 'This hook is called on Admin Security Controller post-process before processing the General form', '1'), (NULL, 'dashboardZoneThree', 'Dashboard column three', 'This hook is displayed in the third column of the dashboard', '1'), (NULL, 'actionPresentPaymentOptions', 'Payment options Presenter', 'This hook is called before payment options are presented', '1'), (NULL, 'actionCustomerLogoutBefore', 'Before customer logout', 'This hook allows you to execute code before customer logout', '1'), (NULL, 'actionCustomerLogoutAfter', 'After customer logout', 'This hook allows you to execute code after customer logout', '1'), (NULL, 'displayCheckoutSummaryTop', 'Cart summary top', 'This hook allows you to display new elements in top of cart summary', '1') (NULL, 'displayCheckoutBeforeConfirmation', 'Show custom content before checkout confirmation', 'This hook allows you to display custom content at the end of checkout process', '1'): You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '(NULL, 'displayCheckoutBeforeConfirmation', 'Show custom content before checkout' at line 11`

But it seems the upgrade is done:

![image](https://user-images.githubusercontent.com/23308427/161753656-94c2deab-db62-4896-8132-bc22aeb0a269.png)
 
Then, when I tried to log in, I get this :trollface: 

![image](https://user-images.githubusercontent.com/23308427/161753796-064ac8ec-32ea-406a-81a7-3831bc878ca8.png)

Waiting for your feedback.
Thanks!

2022-04-05 12:33 UTC, kpodemski commented on upgrade/sql/8.0.0.sql
>    (NULL, 'displayCheckoutSummaryTop', 'Cart summary top', 'This hook allows you to display new elements in top of cart summary', '1')
```suggestion
  (NULL, 'displayCheckoutSummaryTop', 'Cart summary top', 'This hook allows you to display new elements in top of cart summary', '1'),
```

whoops

2022-04-05 12:34 UTC, kpodemski requested changes
I think you missed the comma :)

2022-04-05 15:37 UTC, kpodemski approved these changes

2022-04-08 09:42 UTC, PierreRambaud approved these changes

2022-04-12 12:03 UTC, hibatallahAouadni commented
Hello @Hlavtox 

Thanks for fixing the issue :pray: 
The upgrade is done with success, see the attached screenshot below:

![image](https://user-images.githubusercontent.com/23308427/162951744-cc8a249a-23e2-42fc-993d-75dc4fe30a07.png)

![image](https://user-images.githubusercontent.com/23308427/162958424-b27500c3-b7bf-4d6e-b4d7-1adead172bb0.png)

LGTM, QA :heavy_check_mark: 

Thanks!

2022-04-12 12:05 UTC, merged

2022-04-12 12:05 UTC, Progi1984 commented
Thanks @Hlavtox & @hibatallahAouadni

2022-04-12 12:10 UTC, Hlavtox commented
Yaaaaay