Add hooks displayAdminThemesListAfter and displayModuleConfigureExtraButtons for 8.0.0
PrestaShop/autoupgrade pull request #462
Opened 2022-02-22 17:15 UTC by sowbiba

| Questions         | Answers
| ------------------| -------------------------------------------------------
| Description?      | Add hooks displayAdminThemesListAfter and displayModuleConfigureExtraButtons for autoupgrade of 8.0.0
| Type?             | new feature
| BC breaks?        | no
| Deprecations?     | no
| Fixed ticket?     | See https://github.com/PrestaShop/PrestaShop/pull/27469 and https://github.com/PrestaShop/PrestaShop/pull/27461
| How to test?      | -
| Possible impacts? | -

2022-02-23 13:14 UTC, jolelievre approved these changes

2022-02-25 07:57 UTC, Progi1984 submitted a review, later dismissed

2022-03-09 14:33 UTC, PierreRambaud commented on upgrade/sql/8.0.0.sql
> +  (NULL, 'displayModuleConfigureExtraButtons', 'Module configuration - After toolbar buttons', 'This hook allows to add toolbar''s additional content on module configuration page', '1')
```suggestion
  (NULL, 'displayCheckoutSummaryTop', 'Cart summary top', 'This hook allows you to display new elements in top of cart summary', '1'),
  (NULL, 'displayAdminThemesListAfter', 'BO themes list extra content', 'This hook displays content after the themes list in the BackOffice', '1'),
  (NULL, 'displayModuleConfigureExtraButtons', 'Module configuration - After toolbar buttons', 'This hook allows to add toolbar''s additional content on module configuration page', '1')
```

2022-03-09 14:33 UTC, PierreRambaud requested changes
The SQL is broken ^^

2022-03-09 16:23 UTC, sowbiba commented
> The SQL is broken ^^

oups. Fixed

2022-03-14 08:50 UTC, PierreRambaud approved these changes

2022-03-15 07:52 UTC, Progi1984 approved these changes

2022-03-15 10:53 UTC, AureRita requested changes
Hi @sowbiba, 

I tested it and hooks that you add for autoupgrade isn't show, 

as you can see on this video 

Can't change hooks of Autoupgrade 
https://user-images.githubusercontent.com/100699445/158362434-e9205f2c-4538-4744-b098-479639af519a.mp4

2022-03-21 11:31 UTC, atomiix approved these changes

2022-03-21 15:21 UTC, PierreRambaud submitted a review, later dismissed

2022-04-11 13:53 UTC, PululuK submitted a review, later dismissed

2022-04-12 09:59 UTC, PululuK submitted a review, later dismissed

2022-04-13 12:01 UTC, PierreRambaud requested changes
Unfortunately, this PR needs to be rebased

2022-04-19 08:12 UTC, Progi1984 approved these changes

2022-04-19 12:31 UTC, AureRita commented
hi @sowbiba 

I don't see any label, it is waiting for QA ? =)

2022-04-20 14:41 UTC, sowbiba commented
We normally have to wait for the 2nd approval. But, as it's just a rebase, you can start your testing ;)

2022-04-25 16:24 UTC, AureRita commented
Hi @sowbiba 

I do an autoupdate from 1.7.8.5 to 8.0.0 and we have some exceptions : 

On BO : 
Modules > Modules Managers : 
![image](https://user-images.githubusercontent.com/100699445/165124273-993dc776-fbfc-4815-9b59-89bc8d331dc3.png)

Modules > Modules Catalog 
![image](https://user-images.githubusercontent.com/100699445/165124710-50649672-36a6-4f65-9ddc-ce5bd77efd34.png)

instead of : 
![image](https://user-images.githubusercontent.com/100699445/165124874-d2f57cbf-1278-4703-8f2e-c00f27e0f0d0.png)
(it's known issue) 

Design > Theme Catalog
![image](https://user-images.githubusercontent.com/100699445/165129904-72d7dbfa-858d-4562-a5e4-25104ae5d219.png)

Design > Positions 
![image](https://user-images.githubusercontent.com/100699445/165130011-406665fd-6b53-4bc7-b812-8c20a474283c.png)

Payment > Payment Methods : 
![image](https://user-images.githubusercontent.com/100699445/165130197-5d4e8602-1e0b-4ec2-bf7a-834e87d98b09.png)

Payment > Preferences 
![image](https://user-images.githubusercontent.com/100699445/165130280-233d6b7b-7e97-4e67-8a01-c07334b79085.png)

International > Translations 
![image](https://user-images.githubusercontent.com/100699445/165130476-dae2df71-5546-41e5-8d5e-efacf010ebc3.png)

Marketing 
![image](https://user-images.githubusercontent.com/100699445/165129904-72d7dbfa-858d-4562-a5e4-25104ae5d219.png)

Because of the exception on Design > Position, I can't check the hook on autoupgrade, I see that's a common issue between all these pages 

Thank you for persisting on this pr

2022-04-25 22:04 UTC, sowbiba commented
Hello @AureRita , you choosed a non working module to install (Gamiphy)

If you want to test a working module with configure page, you can use
[prestashopexamplemodule.zip](https://github.com/PrestaShop/autoupgrade/files/8558291/prestashopexamplemodule.zip)
 or Email Templates Manager in the modules catalog page

2022-04-26 07:40 UTC, AureRita commented
Hello @sowbiba 

I tested you PR with an autoupgrade from 1.7.8.5 to 8.0.0, I deleted the module gamiphy (it break the design> position and other tab as you say it) but currently, the module autoupgrade didn't have other hook as you can see :

https://user-images.githubusercontent.com/100699445/165247446-095bfc9c-b5ad-4465-96ba-7a86e7b89167.mp4

2022-04-26 09:17 UTC, sowbiba commented
I understand now. My hook is not an autoupgrade hook, it's a BO hook. In the list of hooks Design > Positions, just filter with the names (displayAdminThemesListAfter and displayModuleCOnfigureExtraButtons) to have them

2022-04-26 13:38 UTC, sowbiba commented
Thanks @AureRita

2022-04-26 13:38 UTC, merged