Added stock_mvt tables upgrade
PrestaShop/autoupgrade pull request #496
Opened 2022-08-11 08:46 UTC by margud

| Questions         | Answers
| ------------------| -------------------------------------------------------
| Description?      | Changing the stock_mvt tables quantity input to unsigned. It is always positive number and by doing this we can insert twice as big int and after this [PR](https://github.com/PrestaShop/PrestaShop/pull/29081) we need that.
| Type?             | improvement 
| BC breaks?        |  no
| Deprecations?     | no
| Fixed ticket?     | Fixes [27313](https://github.com/PrestaShop/PrestaShop/issues/27313).
| How to test?      | Run upgrade and check if table stock_mvt had the column physical_quantity changed to UNSIGNED.

2022-08-17 09:13 UTC, jolelievre reviewed
Thanks @margud

2022-08-17 09:13 UTC, jolelievre approved these changes

2022-09-07 17:58 UTC, jolelievre reviewed
Hi @margud 

this one needs to be rebased because conflicts arose when another one was merged.
Don't hesitate to add you change in the middle of the file instead of the bottom, this should reduce the risk for future conflicts 😉

2022-10-14 12:47 UTC, Robin-Fischer-PS commented
Hi,

Once ready, this one can be tested by a dev :)

2022-10-14 14:07 UTC, jolelievre requested changes
As I suggested in the related PR, this should be handled in v8.1 instead, so the modification should be moved into the `8.1.0.sql` file instead

2023-01-06 13:48 UTC, closed without merging