Add and fill combination lang table
PrestaShop/autoupgrade pull request #534
Opened 2022-12-09 14:31 UTC by Hlavtox

| Questions         | Answers
| ------------------| -------------------------------------------------------
| Description?      | Autoupgrade PR for https://github.com/PrestaShop/PrestaShop/pull/29411
| Type?             | new feature
| BC breaks?        | no
| Deprecations?     | no
| Fixed ticket?     | -
| How to test?      | Have some products with combinations. Do upgrade to 8.1 and check that new table `ps_product_attribute_lang` with data is created. Try to edit some combinations, should work fine.
| Possible impacts? | no

2022-12-12 15:48 UTC, nicosomb approved these changes

2022-12-15 10:28 UTC, MhiriFaten reviewed
Hello @Hlavtox ,

I tried to check the PR autoupgrade:

upgrade **1788** to **800** OK :heavy_check_mark: 
upgrade **1788** to release **develop** is NOK :x:  as it mentioned in '**how to test**' to do upgrade to `8.1`

![image](https://user-images.githubusercontent.com/111756615/207835408-914a8791-5545-4ac5-87d9-9fd4a07f32ca.png)


Could you check it please ?
Waiting for your feedback ! 

Thank you.

2022-12-23 14:16 UTC, MhiriFaten reviewed
Hello @Hlavtox ,

I have enabled the debug mode and here is the error message :

![image](https://user-images.githubusercontent.com/111756615/209349118-5aeaba59-b00a-40dd-a02d-30cb2103c9bf.png)

`[INTERNAL] /var/www/html/autoupgrade1788/vendor/symfony/symfony/src/Symfony/Component/DependencyInjection/Compiler/DefinitionErrorExceptionPass.php line 54 - Symfony\Component\DependencyInjection\Exception\RuntimeException: You have requested a non-existent parameter "api_private_key". #0 /var/www/html/autoupgrade1788/vendor/symfony/symfony/src/Symfony/Component/DependencyInjection/Compiler/AbstractRecursivePass.php(83): Symfony\Component\DependencyInjection\Compiler\DefinitionErrorExceptionPass->processValue(Object(Symfony\Component\DependencyInjection\Definition), true) #1 /var/www/html/autoupgrade1788/vendor/symfony/symfony/src/Symfony/Component/DependencyInjection/Compiler/DefinitionErrorExceptionPass.php(32): Symfony\Component\DependencyInjection\Compiler\AbstractRecursivePass->processValue(Array, true) #2 /var/www/html/autoupgrade1788/vendor/symfony/symfony/src/Symfony/Component/DependencyInjection/Compiler/AbstractRecursivePass.php(47): Symfony\Component\DependencyInjection\Compiler\DefinitionErrorExceptionPass->processValue(Array, true) #3 /var/www/html/autoupgrade1788/vendor/symfony/symfony/src/Symfony/Component/DependencyInjection/Compiler/Compiler.php(94): Symfony\Component\DependencyInjection\Compiler\AbstractRecursivePass->process(Object(Symfony\Component\DependencyInjection\ContainerBuilder)) #4 /var/www/html/autoupgrade1788/vendor/symfony/symfony/src/Symfony/Component/DependencyInjection/ContainerBuilder.php(762): Symfony\Component\DependencyInjection\Compiler\Compiler->compile(Object(Symfony\Component\DependencyInjection\ContainerBuilder)) #5 /var/www/html/autoupgrade1788/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/Kernel.php(594): Symfony\Component\DependencyInjection\ContainerBuilder->compile() #6 /var/www/html/autoupgrade1788/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/Kernel.php(136): Symfony\Component\HttpKernel\Kernel->initializeContainer() #7 /var/www/html/autoupgrade1788/app/AppKernel.php(87): Symfony\Component\HttpKernel\Kernel->boot() #8 /var/www/html/autoupgrade1788/modules/autoupgrade/classes/UpgradeTools/SymfonyAdapter.php(76): AppKernel->boot() #9 /var/www/html/autoupgrade1788/modules/autoupgrade/classes/UpgradeTools/CoreUpgrader/CoreUpgrader80.php(44): PrestaShop\Module\AutoUpgrade\UpgradeTools\SymfonyAdapter->initAppKernel() #10 /var/www/html/autoupgrade1788/modules/autoupgrade/classes/UpgradeTools/CoreUpgrader/CoreUpgrader.php(87): PrestaShop\Module\AutoUpgrade\UpgradeTools\CoreUpgrader\CoreUpgrader80->initConstants() #11 /var/www/html/autoupgrade1788/modules/autoupgrade/classes/TaskRunner/Upgrade/UpgradeDb.php(42): PrestaShop\Module\AutoUpgrade\UpgradeTools\CoreUpgrader\CoreUpgrader->doUpgrade() #12 /var/www/html/autoupgrade1788/admin-dev/autoupgrade/ajax-upgradetab.php(53): PrestaShop\Module\AutoUpgrade\TaskRunner\Upgrade\UpgradeDb->run() #13 {main}`

After having the error of the upgrade, I can no longer go to any other page
![image](https://user-images.githubusercontent.com/111756615/209349208-927bf353-fe4d-48ee-ba08-b5a76105749f.png)

- Upgrade from **1.7.8.8** to **8.1.0** with autoupgrade **v4.15.0**

[Untitled_ Dec 23, 2022 2_59 PM.webm](https://user-images.githubusercontent.com/111756615/209349822-d9575d1e-9273-4635-ae2a-0fbd91a4f811.webm)

I hope these details can help you :pray: 

Many thanks.

2023-01-12 14:10 UTC, Hlavtox commented
Unblocked, PR may need a rebase to work.

2023-01-12 14:14 UTC, Hlavtox commented
@MhiriFaten Everything should be ready, you can test the upgrade to 8.1. 👍

2023-01-17 08:40 UTC, Hlavtox commented
@hibatallahAouadni Do you want to remove waiting for QA also here?

2023-01-17 08:50 UTC, jolelievre approved these changes
Thanks @Hlavtox

2023-01-17 14:22 UTC, Hlavtox commented
@HanaRebaiQA Thanks! Rebased! :-)

2023-01-17 14:32 UTC, SharakPL requested changes

2023-01-17 14:32 UTC, SharakPL commented on upgrade/php/ps_810_add_product_attribute_lang_data.php
> +    }
```suggestion
    foreach (Language::getLanguages() as $language) {
        Db::getInstance()->execute(
            'INSERT INTO ' . _DB_PREFIX_ . 'product_attribute_lang 
            (id_product_attribute, id_lang, available_now, available_later)
            SELECT pa.id_product_attribute, ' . (int) $language['id_lang'] . ", '', ''
            FROM " . _DB_PREFIX_ . 'product_attribute pa'
        );
    }
```

2023-01-17 14:47 UTC, kpodemski approved these changes

2023-01-18 13:35 UTC, HanaRebaiQA approved these changes
Hello @Hlavtox 

I have checked again your PR. 

This same list as mentioned [here](https://github.com/PrestaShop/autoupgrade/pull/534#pullrequestreview-1251629262) is checked again : 

- Check with upgrade from 1778 to 8.1.0 : OK :heavy_check_mark: 
- Check with upgrade from 1788 to 8.1.0 : OK :heavy_check_mark: 
- Check with different php version (php7.4, php7.3) : OK :heavy_check_mark: 

![image](https://user-images.githubusercontent.com/92912932/213185261-1c709433-e946-4bcc-9e9d-c570bc7c6fd1.png)

![image](https://user-images.githubusercontent.com/92912932/213185098-c3d42174-4429-4af0-8711-ddb3710f3300.png)

So, it's QA :heavy_check_mark: 

Thanks!

2023-01-18 13:39 UTC, merged

2023-01-18 13:39 UTC, Hlavtox commented
perfectoooo