Fixed lines which are not compatible with PHP < 7
PrestaShop/autoupgrade pull request #585
Opened 2023-05-29 12:02 UTC by nicosomb

| Questions         | Answers
| ------------------| -------------------------------------------------------
| Description?      | See https://github.com/PrestaShop/autoupgrade/pull/442 
| Type?             | bug fix 
| BC breaks?        | no
| Deprecations?     | no
| Fixed ticket?     | Related to https://github.com/PrestaShop/PrestaShop/issues/27087 
| Sponsor company   | PrestaShop SA 
| How to test?      | See https://github.com/PrestaShop/autoupgrade/pull/442

2023-05-29 13:30 UTC, matthieu-rolland reviewed
I restarted the upgrade tests

otherwise, LGTM :+1:

2023-05-29 14:07 UTC, jolelievre approved these changes
Thanks @nicosomb

2023-05-29 17:12 UTC, jolelievre approved these changes

2023-05-30 08:03 UTC, 0x346e3730 approved these changes

2023-05-30 09:03 UTC, 0x346e3730 approved these changes

2023-05-30 09:05 UTC, FabienPapet approved these changes

2023-05-30 09:09 UTC, boherm approved these changes

2023-05-30 13:20 UTC, hibatallahAouadni reviewed
Hello @nicosomb 

Thanks for your PR 🚀 
Unfortunately I couldn't upgrade my shop as the base branch of PR is 4.14 while the latest version of the module is 4.15, so the button upgrade will not be displayed till the version will upgraded, see the attached screen record below:

[pr_585.webm](https://github.com/PrestaShop/autoupgrade/assets/23308427/2a23af0a-23c3-4261-b5e8-d8148ccdfed2)

Please check and feedback.

Thanks!

2023-05-30 15:20 UTC, matthieu-rolland approved these changes

2023-06-02 09:42 UTC, nicosomb commented
@hibatallahAouadni could you write here what do you expect please? 
I'm not an autoupgrade expert. 
Do you expect a button? Do you expect to upgrade only to a 1.7.x release? 

Thank you for your help.

2023-06-02 09:50 UTC, hibatallahAouadni commented
Hello @nicosomb 

Sorry for being unclear :pray: let me explain :wink: 
If there's one requirement not satisfied, the button "upgrade now" will not be displayed.
As you can I have one requirement not statisfied, it seems that the system see that the module autoupgrade is not up to date.
So I can't upgrade my shop cause the button is not displayed.
I hope I have been clear :sweat_smile: 

Good luck and thanks!

2023-06-05 08:53 UTC, jolelievre requested changes

2023-06-05 08:53 UTC, jolelievre commented on autoupgrade.php
The version complicancy `$this->ps_versions_compliancy = array('min' => '1.6.0.0', 'max' => _PS_VERSION_);` should be updated and max version should be `1.7.8.9`

Also when providing the list pf possible updates, when the source is 1.6 the max version allowed should also be 1.7.8.9 (ideally based on the ps_versions_compliancy settings, but if it's hard-coded for now it could be acceptable)

2023-06-18 06:47 UTC, closed without merging