Release module 4.16.0
PrestaShop/autoupgrade pull request #592
Opened 2023-06-19 08:18 UTC by jolelievre

| Questions         | Answers
| ------------------| -------------------------------------------------------
| Description?      | Release module 4.16.0
| Type?             | new feature
| BC breaks?        | no
| Deprecations?     | no
| Fixed ticket?     | ~
| Sponsor company   | ~
| How to test?      | ~

2023-06-19 08:20 UTC, nicosomb approved these changes

2023-06-19 08:23 UTC, kpodemski approved these changes

2023-06-21 09:22 UTC, florine2623 approved these changes
Hello @jolelievre ,

Here are the upgrade tests done :

`1.7.8.9 -> 8.0.4 -> 8.1.0 ` tested by @MhiriFaten 
Old issue reproduced : https://github.com/PrestaShop/PrestaShop/issues/32953
Autoupgrade 1.7.8.9->8.0.4->8.1.0 ✅ 
Rollback 8.0.4->8.1.0 ✅ 
Rollback 8.0.4 ->1.7.8.9 ✅ 

`1.6.1.24 -> 8.0.4 -> 8.1.0` and `1.6.1.24 -> 8.1.0` tested by @florine2623 
Can't be tested at the moment (already discussed with @MatShir )

`1.7.8.9 -> 8.1.0` tested by @AureRita 
Exception found once, but couldn't be reproduce another time.
Autoupgrade 1.7.8.9 -> 8.1.0 ✅
Rollback 1.7.8.9 -> 8.1.0 ✅

`8.0.4 -> 8.1.0` tested by @aniszr
Issue detected, but only because of cache.
Autoupgrade 8.0.4 -> 8.1.0 ✅
Rollback 8.0.4 -> 8.1.0 ✅

No regression detected, so it is a GO for the QA team ✅

2023-06-21 09:25 UTC, MatShir requested changes
Should we wait the E2E test to validate the new release? @jolelievre @Progi1984 @Robin-Fischer-PS

2023-06-26 08:44 UTC, boherm approved these changes

2023-06-26 08:55 UTC, merged