Add key check
PrestaShop/autoupgrade pull request #599
Opened 2023-07-19 09:47 UTC by Hlavtox

| Questions         | Answers
| ------------------| -------------------------------------------------------
| Description?      | Adds warning about key generation in order not to crash the upgrade. Error shows up only if it fails, in order not to make the table kilometer long. :-) They key is only checked when upgrading to 8.1.0 or newer.
| Type?             | improvement
| BC breaks?        | no
| Deprecations?     | no
| Fixed ticket?     | Fixes #https://github.com/PrestaShop/PrestaShop/issues/33286
| Sponsor company   | 
| How to test?      | See below

### How to test
- We can see that https://www.php.net/manual/en/function.openssl-pkey-new.php returns a false on failure, which is confirmed by the issue - https://github.com/PrestaShop/PrestaShop/issues/33286.
- So, to test it, put `return false;` to the beginning checkKeyGeneration method in  classes/UpgradeSelfCheck.php. You should see the error message in autoupgrade module afterwards.

### Related core PR
https://github.com/PrestaShop/PrestaShop/pull/33292

### Screenshot
![Snímek obrazovky 2023-07-19 114543](https://github.com/PrestaShop/autoupgrade/assets/6097524/60f8a390-a0ad-4902-89d3-cc9191e067b8)

2023-07-19 14:55 UTC, matthieu-rolland submitted a review, later dismissed
nice additional check, it's a good idea to display it only if it fails :+1:

2023-07-19 14:58 UTC, M0rgan01 submitted a review, later dismissed

2023-07-19 18:38 UTC, kpodemski approved these changes

2023-07-19 18:38 UTC, kpodemski commented
@Hlavtox could you propose a way to test it? 🤔

2023-07-20 09:06 UTC, Hlavtox commented
@kpodemski I extended the PR description, is it OK?

2023-08-01 05:23 UTC, hibatallahAouadni commented
@kpodemski do you see that a Dev should test both PRs https://github.com/PrestaShop/PrestaShop/pull/33292 and this one, or a QA may test it with a Developer's help? wdyt?

2023-08-01 09:58 UTC, kpodemski requested changes
The check should be only for 8.1+

2023-08-01 14:39 UTC, kpodemski approved these changes

2023-08-02 07:54 UTC, kpodemski approved these changes

2023-08-02 07:55 UTC, kpodemski commented
I had to manually return false for the function as I don't know any broken environment and it is working fine :)

2023-08-02 07:55 UTC, merged