Update 8.1.3.sql
PrestaShop/autoupgrade pull request #645
Opened 2023-11-12 11:26 UTC by ShaiMagal

| Questions         | Answers
| ------------------| -------------------------------------------------------
| Description?      | Related to PR #54530 (https://github.com/PrestaShop/PrestaShop/pull/34530)
| Type?             | bug fix
| BC breaks?        | no
| Deprecations?     | no
| Fixed ticket?     | Fixes #30022
| Related PRs     | #34530
| Sponsor company   | https://www.openservis.cz/
| How to test?      |

2023-11-12 12:17 UTC, Hlavtox reviewed
Although this will work perfectly, there could be a possible performance caveat with rebuilding the whole table. 🤔

I think it would be better to go for a php solution.

2023-11-24 13:25 UTC, tleon approved these changes

2023-12-06 08:18 UTC, kpodemski commented
@Hlavtox it's a valid solution

2023-12-06 08:19 UTC, kpodemski requested changes
It looks good, but it should be part of 9.0.0.sql following the PR that is for the `develop` branch.

2024-04-03 22:07 UTC, ShaiMagal commented
@Hlavtox can you suggest php way of this? I am not familiar with this.

2024-04-20 04:13 UTC, Hlavtox commented
@ShaiMagal 9.0.0.sql please ;-)

2024-05-07 13:50 UTC, Quetzacoalt91 commented
Closed in favor of https://github.com/PrestaShop/autoupgrade/pull/689

2024-05-07 13:50 UTC, closed without merging