Release version 5.0.1
PrestaShop/autoupgrade pull request #668
Opened 2024-01-30 13:20 UTC by Hlavtox

| Questions         | Answers
| ------------------| -------------------------------------------------------
| Description?      | Release version 5.0.1
| Type?             | 
| BC breaks?        | 
| Deprecations?     | 
| Fixed ticket?     | 
| Sponsor company   |
| How to test?      |

2024-01-31 09:11 UTC, Hlavtox commented
@PrestaShop/qa-functional One quick upgrade from 1.7.8 to 8.1 should be sufficient, not much changed.

2024-01-31 09:11 UTC, ShaiMagal submitted a review, later dismissed

2024-02-20 13:59 UTC, matks commented
Blocked by https://github.com/PrestaShop/autoupgrade/pull/671

2024-02-20 14:16 UTC, jolelievre requested changes

2024-02-20 14:16 UTC, jolelievre commented on upgrade/sql/8.1.4.sql
I think this one should be renamed into `8.1.5.sql` first, the `8.1.4` was released separately as a security version

2024-02-20 14:27 UTC, jolelievre approved these changes

2024-02-26 10:39 UTC, Hlavtox commented
After CI is fixed in https://github.com/PrestaShop/autoupgrade/pull/673 we can go on

2024-02-26 16:36 UTC, ShaiMagal approved these changes

2024-02-27 11:09 UTC, AureRita approved these changes
Hi @Hlavtox 

Thank you for your PR, I tested it and it seems to works as you can see : 

[recording(117).webm](https://github.com/PrestaShop/autoupgrade/assets/100699445/c69c1465-b954-46c8-a320-07d58b0b4a6b)

I tested to upgrade from 1.7.8.11 to 8.0.5 to 8.1.4
I do a rollboack to 8.0.5 and to 1.7.8.11 

Because the PR seems to works as expected, It's QA :heavy_check_mark: 

Thank you

2024-02-27 11:12 UTC, merged