Update 9.0.0.sql
PrestaShop/autoupgrade pull request #691
Opened 2024-04-18 13:57 UTC by Kaikina

See PR prestashop/prestashop#35843

| Questions         | Answers
| ------------------| -------------------------------------------------------
| Description?      | Goes along the PR prestashop/prestashop#35843 from prestashop/prestashop. A new configuration key is added to the core. It should be inserted in the next version autoupgrade script.
| Type?             | improvement
| BC breaks?        | no
| Deprecations?     | no
| Fixed ticket?     |  NA
| Sponsor company   | Evolutive
| How to test?      | NA

2024-04-18 14:07 UTC, Kaikina commented
Related PR : https://github.com/PrestaShop/PrestaShop/pull/35843

2024-04-18 14:24 UTC, Touxten approved these changes

2024-04-18 15:41 UTC, LouisAUTHIE submitted a review, later dismissed

2024-04-30 12:45 UTC, nicosomb approved these changes, later dismissed

2024-05-22 08:18 UTC, Hlavtox commented
@Kaikina Rebase is needed

2024-05-27 09:19 UTC, Kaikina commented
Done @Hlavtox

2024-05-27 10:35 UTC, Hlavtox requested changes
PR broken, some merge things got into it

2024-05-30 08:01 UTC, Kaikina commented
@Hlavtox how about now ?

2024-06-20 13:23 UTC, ga-devfront approved these changes

2024-06-20 14:03 UTC, Hlavtox approved these changes

2024-07-08 08:54 UTC, AureRita commented
Hi @Kaikina 

Currently I see that your [PR](https://github.com/PrestaShop/PrestaShop/pull/35843) isn't merged on develop, I'll block this PR until your PR 'll be merged 

Thank you

2024-10-21 13:09 UTC, kpodemski approved these changes

2024-10-21 13:09 UTC, kpodemski commented
PR against the core has been merged. I removed the "Blocked" label.

2024-10-24 15:48 UTC, AureRita commented
Hi @Kaikina !

Thank you for your PR, Currently I tried to see the difference with the 9.0.0 like have a new field to set up the new separators but as you can see, that doesn't seems to works : 

[recording(313).webm](https://github.com/user-attachments/assets/e97970e2-9964-4b15-be27-482aab5b7347)

![image](https://github.com/user-attachments/assets/213a91c4-5f49-479d-a1ec-a146f67c214e)


Did I forget anything ? 

Waitinf gor your feedback

2024-10-25 14:26 UTC, jf-viguier commented
@AureRita have you clone the core in the 9.0.x branch ? The other PR isn't in develop branch I guess ?

2024-10-25 14:28 UTC, Hlavtox commented
@AureRita Why are you testing an already tested and merged feature?

Only thing that should be QAd now is if PS_SEPARATOR_FILE_MANAGER_SQL is in the database after upgrade.

2024-11-14 10:53 UTC, AureRita commented
Hi @Kaikina 

Thank you for your PR, I tested it and it seems to works as you can see : 

![image](https://github.com/user-attachments/assets/a32fdfb8-0591-4454-a782-4db00b7c7956)


Tested from : 
8.2 to 9.0.0
8.0.4 to 9.0.0

Because the PR seems to works as expected, It's QA :heavy_check_mark: 

Thank you

2024-11-14 10:54 UTC, AureRita approved these changes

2024-11-14 11:20 UTC, merged

2024-11-14 11:20 UTC, ps-jarvis commented
<!-- PR_MISSING_MILESTONE -->
PR merged, well done!

Message to @PrestaShop/committers: do not forget to milestone it before the merge.