Improve requirements for v7.0.0
PrestaShop/autoupgrade pull request #867
Opened 2024-09-03 13:33 UTC by M0rgan01

…ome clean

| Questions         | Answers
| ------------------| -------------------------------------------------------
| Description?      | Certain requirements disappeared with v7, I also have a function to recover the wording to unify it between the CLI and the web version.
| Type?             | improvement
| BC breaks?        | no
| Deprecations?     | no
| Fixed ticket?     | -
| Sponsor company   | -
| How to test?      | -

2024-09-04 14:56 UTC, Quetzacoalt91 commented on classes/UpgradeSelfCheck.php
> +        ];
If we're supposed to return only display errors, this method could return only the detected issues. Something OK would not appear.

And if you only return the issues, you could generate at this time the translated message? By doing so you would call trans only when necessary.

2024-09-04 15:16 UTC, Quetzacoalt91 submitted a review, later dismissed

2024-09-04 15:37 UTC, Quetzacoalt91 approved these changes

2024-09-04 15:45 UTC, M0rgan01 commented
@Hlavtox Yes it is voluntary. This verification is already done by PrestaShop itself since PrestaShop 1.7, so we are dropping it. There will be problems before you even get to the module screen

2024-09-04 15:49 UTC, Quetzacoalt91 submitted a review, later dismissed

2024-09-04 15:51 UTC, ga-devfront approved these changes

2024-09-09 09:53 UTC, Quetzacoalt91 commented on classes/UpgradeSelfCheck.php
> +            self::PHP_REQUIREMENTS_INVALID => $this->getPhpRequirementsState() == self::PHP_REQUIREMENTS_INVALID,
```suggestion
            self::PHP_REQUIREMENTS_INVALID => $this->getPhpRequirementsState() === self::PHP_REQUIREMENTS_INVALID,
```

2024-09-09 09:53 UTC, Quetzacoalt91 commented on classes/UpgradeSelfCheck.php
> +            self::PHP_REQUIREMENTS_UNKNOWN => !$this->getPhpRequirementsState() == self::PHP_REQUIREMENTS_UNKNOWN,
```suggestion
            self::PHP_REQUIREMENTS_UNKNOWN => $this->getPhpRequirementsState() === self::PHP_REQUIREMENTS_UNKNOWN,
```

2024-09-09 12:26 UTC, Quetzacoalt91 submitted a review, later dismissed

2024-09-11 08:07 UTC, Quetzacoalt91 approved these changes

2024-09-11 08:17 UTC, Hlavtox requested changes
@M0rgan01 Please check this - https://github.com/PrestaShop/autoupgrade/pull/561

I specifically implemented the session check inside this module, because the core check was faulty.

2024-09-11 08:44 UTC, M0rgan01 commented
@Hlavtox While waiting to investigate the subject of PHP sessions, I am removing it from the PR so as not to block it

2024-09-11 12:39 UTC, Quetzacoalt91 commented
> @M0rgan01 Please see this - #561
> 
> I specifically implemented the session check inside this module, because the core check was faulty. I made the change to fix this issue - [PrestaShop/PrestaShop#30658](https://github.com/PrestaShop/PrestaShop/issues/30658).

@Hlavtox considering all the versions currently supported by the autoupgrade module require sessions to work properly, is this check still relevant in the module before an update?
I guess that if sessions don't work properly, the installation would have detected it, or in the worst case an error would have been thrown while using the backoffice or something?

2024-09-11 12:43 UTC, Hlavtox commented
@Quetzacoalt91 Well, the problem was that even though sessions worked, the check present in the core did not.

So, if you want to completely skip this check, we can remove it, because if he go to the screen, the sessions work.
But, if you want to use the CORE check, it won't work for pre 8.0 cores, I fixed the issue for 8.0.x - https://github.com/PrestaShop/PrestaShop/pull/31241

2024-09-11 16:20 UTC, AureRita approved these changes
Hi @M0rgan01 

Thank you for your PR, I tested it and it seems to works as you can see : 

![image](https://github.com/user-attachments/assets/32908187-e677-47ec-b61e-e73020dcd04e)

Tested from : 
1.7.7.8 to 8.1.7 
8.0.5 to 8.1.7 
8.1.7 to 9.0.0
8.1.5 to 9.0.0
8.0.5 to 9.0.0

Because the PR seems to works as expected, It's QA :heavy_check_mark: 

Thank you

2024-09-11 16:22 UTC, merged

2024-09-12 09:20 UTC, Hlavtox commented on classes/UpgradeSelfCheck.php
> +                    [$phpFunctionsCount > 1 ? 's' : '', $phpFunctionsCount === 1 ? 's' : '']
This doesn't work for other languages. :-)

2024-09-12 10:02 UTC, Quetzacoalt91 commented
I've heard of this feature, but I wasn't sure it can be used. Seeing the opened PR seems to confirm there is no such thing on the Core? :/
We'll check again, thanks for the feedback in the meantime.

2024-09-12 10:18 UTC, Hlavtox commented
@Quetzacoalt91 Symfony supports it out of the box, and it worked when I tried it, but it would require some minor tweaks. :-)

It's the proper way to do plurals in all languages.
Example:
- English:
  - 0 items
  - 1 item
  - 2 items
  - 3 items
  - 4 items etc.
- Czech:
  - 0 položek
  - 1 položka
  - 2 položky
  - 3 položky
  - 4 položky
  - 5 položek
  - 6 položek etc.