Update upgrade.js
PrestaShop/autoupgrade pull request #906
Opened 2024-09-21 00:23 UTC by fer-av

versionNumberRegex Not define!!!

| Questions         | Answers
| ------------------| -------------------------------------------------------
| Description?      | No anda Expert mode -> Canal: directorio local
| Type?             | bug fix 
| BC breaks?        | yes 
| Deprecations?     | yes 
| Fixed ticket?     | 
| Sponsor company   | eflyshop
| How to test?      | hice el cambio y actualice mi sitio!

2024-09-21 00:24 UTC, ps-jarvis commented
<!-- PR_WELCOME -->
Hello @fer-av!

This is your first pull request on [autoupgrade](https://github.com/PrestaShop/autoupgrade/) repository of the PrestaShop project.

Thank you, and welcome to this Open Source community!

2024-09-22 04:20 UTC, Seb33300 requested changes

2024-09-22 04:20 UTC, Seb33300 commented on js/upgrade.js
> +      var versionNumberRegex = /^\d+(.\d+){2,3}$/; // versionNumberRegex no definada, la agregue
```suggestion
      var versionNumberRegex = /^\d+(.\d+){2,3}$/;
```

2024-09-23 12:55 UTC, M0rgan01 commented
@fer-av Hello! Thanks for the contribution, and for restoring the missing variable!

 However, the upgrade.js file will be completely refactored into typescript for the introduction of a new UI on the next major release.

2024-09-25 15:05 UTC, Quetzacoalt91 commented
This variable is indeed not used anymore in the upgrade.js file on the `dev` branch, and the incoming version will provide a new UI.

I changed the base branch for 6.x but it requires a rebase on your end.

2024-12-02 10:51 UTC, Quetzacoalt91 approved these changes

2024-12-09 10:38 UTC, AureRita approved these changes
Hi @fer-av 

Thank you for your PR, I tested it and it seems to works as you can see : 

[recording(13).webm](https://github.com/user-attachments/assets/dfd260d9-1c3e-4e71-8eb5-9b800b261355)


Tested from : 
8.0.4 to 8.2 
8.2 to 9.0.0
8.0.4 to 9.0.0

Because the PR seems to works as expected, It's QA :heavy_check_mark: 

Thank you

2024-12-09 10:42 UTC, merged