[NEW UI] Update requirements
PrestaShop/autoupgrade pull request #921
Opened 2024-09-27 13:26 UTC by tblivet

| Questions         | Answers
| ------------------| -------------------------------------------------------
| Description?      | Update requirements
| Type?             | bug fix
| BC breaks?        | no
| Deprecations?     | no
| Fixed ticket?     | -
| Sponsor company   | @PrestaShopCorp
| How to test?      | Test if the requirements section in Storybook is displayed correctly.

2024-09-30 10:08 UTC, Quetzacoalt91 approved these changes

2024-09-30 10:17 UTC, Quetzacoalt91 requested changes, later dismissed
Actually, we can make the code easier to read and mayber with stricter checks.

2024-09-30 10:17 UTC, Quetzacoalt91 commented on views/templates/components/check-requirements.html.twig
> +            <div class="check-requirements__requirement check-requirements__requirement--warning">
To make the check simpler

```suggestion
        {% if phpRequirementsState === constant('PrestaShop\\Module\\AutoUpgrade\\Services\\PhpVersionResolverService::COMPATIBILITY_UNKNOWN') %}
          <div class="check-requirements__requirement check-requirements__requirement--warning">
```

2024-09-30 10:17 UTC, Quetzacoalt91 commented on views/templates/components/check-requirements.html.twig
> +          {% endif %}
```suggestion
          </div>
```

2024-09-30 10:17 UTC, Quetzacoalt91 commented on views/templates/components/check-requirements.html.twig
> +          {% if phpRequirementsState == constant('PrestaShop\\Module\\AutoUpgrade\\Services\\PhpVersionResolverService::COMPATIBILITY_INVALID') %}
```suggestion
        {% if phpRequirementsState === constant('PrestaShop\\Module\\AutoUpgrade\\Services\\PhpVersionResolverService::COMPATIBILITY_INVALID') %}
```

2024-09-30 10:17 UTC, Quetzacoalt91 commented on views/templates/components/check-requirements.html.twig
>            {% endif %}
```suggestion
```

2024-10-03 06:47 UTC, ga-devfront reviewed
I think it needs to be discussed, but in my opinion the list of requirements will not be hard-coded in the twig.

2024-10-03 08:54 UTC, M0rgan01 approved these changes

2024-10-03 15:29 UTC, merged